ANDROID = "USERAGENTANDROID"
WINDOWS = "USERAGENTWINDOWS"

ALPHABET = "abcdefghijklmnopqrstuvwxyz"
ONEDAY = 60*60*24

BUTTONACTIVEBACKGROUND = "#03396c"
BUTTONIDLEBACKGROUND = "#b3cde0"
BUTTONBORDER = "#005b96"
BUTTONBORDERWIDTH = 1
BUTTONACTIVETEXT = "#FFFFFF"
BUTTONIDLETEXT = "#000000"
BUTTONCLICKEDBACKGROUND = "#6497b1"
BUTTONCLICKEDTEXT = "#000000"
FONT = 'verdana'

REMOVEBUTTONACTIVEBACKGROUND = "#FF0000"
REMOVEBUTTONIDLEBACKGROUND = "#FFDDDD"
REMOVEBUTTONBORDER = "#FFFFFF"
REMOVEBUTTONBORDERWIDTH = 0
REMOVEBUTTONCLICKEDTEXT = "#000000"
REMOVEBUTTONCLICKEDBACKGROUND = "#AA88FF"
REMOVEBUTTONIDLETEXT = "#000000"
REMOVEBUTTONACTIVETEXT = "#FFFFFF"

CORRECTBUTTONACTIVEBACKGROUND = "#ACFFAD"
CORRECTBUTTONIDLEBACKGROUND = "#50CB93"
CORRECTBUTTONBORDER = "#FFFFFF"
CORRECTBUTTONBORDERWIDTH = 0
CORRECTBUTTONCLICKEDTEXT = "#FFFFFF"
CORRECTBUTTONCLICKEDBACKGROUND = "#54436B"
CORRECTBUTTONIDLETEXT = "#54436B"
CORRECTBUTTONACTIVETEXT = "#54436B"

INCORRECTBUTTONACTIVEBACKGROUND = "#FFDDDD"
INCORRECTBUTTONIDLEBACKGROUND = "#FF0000"
INCORRECTBUTTONBORDER = "#FFFFFF"
INCORRECTBUTTONBORDERWIDTH = 0
INCORRECTBUTTONCLICKEDTEXT = "#000000"
INCORRECTBUTTONCLICKEDBACKGROUND = "#AA88FF"
INCORRECTBUTTONIDLETEXT = "#FFFFFF"
INCORRECTBUTTONACTIVETEXT = "#000000"

